name: Android CI
on:
  release:
    types: [published]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2  # 使用 actions/setup-java@v2，根据你的需要更新版本
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: RunWorldSchool-${{ github.event.release.tag_name }}.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip
